# Generated by Django 4.2.7 on 2025-04-01 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
                ('total_lines', models.IntegerField()),
                ('unique_symbols_count', models.IntegerField()),
                ('unique_order_ids_count', models.IntegerField()),
                ('unique_execution_ids_count', models.IntegerField()),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='pitch_api.pitchfile')),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_types', to='pitch_api.pitchfile')),
            ],
        ),
    ]
