# Generated by Django 4.2.7 on 2025-04-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitch_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('trade_id', models.CharField(blank=True, max_length=20, null=True)),
                ('executed_shares', models.IntegerField(blank=True, null=True)),
                ('execution_price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch_api.pitchfile')),
            ],
            options={
                'indexes': [models.Index(fields=['pitch_file', 'trade_id'], name='pitch_api_t_pitch_f_ec9701_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradeBreakMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('trade_id', models.CharField(blank=True, max_length=20, null=True)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch_api.pitchfile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['pitch_file', 'message_type'], name='pitch_api_t_pitch_f_727523_idx'), models.Index(fields=['pitch_file', 'order_id'], name='pitch_api_t_pitch_f_d9c195_idx'), models.Index(fields=['pitch_file', 'symbol'], name='pitch_api_t_pitch_f_e97afe_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemEventMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('event_code', models.CharField(blank=True, max_length=1, null=True)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch_api.pitchfile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['pitch_file', 'message_type'], name='pitch_api_s_pitch_f_7f4cd9_idx'), models.Index(fields=['pitch_file', 'order_id'], name='pitch_api_s_pitch_f_138754_idx'), models.Index(fields=['pitch_file', 'symbol'], name='pitch_api_s_pitch_f_8c8f4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModifyOrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('modified_shares', models.IntegerField(blank=True, null=True)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch_api.pitchfile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['pitch_file', 'message_type'], name='pitch_api_m_pitch_f_4c175f_idx'), models.Index(fields=['pitch_file', 'order_id'], name='pitch_api_m_pitch_f_affeb7_idx'), models.Index(fields=['pitch_file', 'symbol'], name='pitch_api_m_pitch_f_d6dcdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeleteOrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch_api.pitchfile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['pitch_file', 'message_type'], name='pitch_api_d_pitch_f_b08bd1_idx'), models.Index(fields=['pitch_file', 'order_id'], name='pitch_api_d_pitch_f_1b2f58_idx'), models.Index(fields=['pitch_file', 'symbol'], name='pitch_api_d_pitch_f_68fa11_idx')],
            },
        ),
        migrations.CreateModel(
            name='CancelOrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('canceled_shares', models.IntegerField(blank=True, null=True)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch_api.pitchfile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['pitch_file', 'message_type'], name='pitch_api_c_pitch_f_c85d48_idx'), models.Index(fields=['pitch_file', 'order_id'], name='pitch_api_c_pitch_f_4ca484_idx'), models.Index(fields=['pitch_file', 'symbol'], name='pitch_api_c_pitch_f_4c953f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuctionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('auction_type', models.CharField(blank=True, max_length=1, null=True)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('buy_shares', models.IntegerField(blank=True, null=True)),
                ('sell_shares', models.IntegerField(blank=True, null=True)),
                ('indicative_price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch_api.pitchfile')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['pitch_file', 'message_type'], name='pitch_api_a_pitch_f_50e1a5_idx'), models.Index(fields=['pitch_file', 'order_id'], name='pitch_api_a_pitch_f_7aa950_idx'), models.Index(fields=['pitch_file', 'symbol'], name='pitch_api_a_pitch_f_0e96a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AddOrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=19, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
                ('pitch_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitch_api.pitchfile')),
            ],
            options={
                'indexes': [models.Index(fields=['pitch_file', 'side'], name='pitch_api_a_pitch_f_04e451_idx')],
            },
        ),
    ]
