# Generated by Django 4.2.7 on 2025-04-03 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitch_api', '0002_trademessage_tradebreakmessage_systemeventmessage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='addordermessage',
            name='pitch_api_a_pitch_f_04e451_idx',
        ),
        migrations.RemoveIndex(
            model_name='auctionmessage',
            name='pitch_api_a_pitch_f_50e1a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='auctionmessage',
            name='pitch_api_a_pitch_f_7aa950_idx',
        ),
        migrations.RemoveIndex(
            model_name='cancelordermessage',
            name='pitch_api_c_pitch_f_c85d48_idx',
        ),
        migrations.RemoveIndex(
            model_name='cancelordermessage',
            name='pitch_api_c_pitch_f_4c953f_idx',
        ),
        migrations.RemoveIndex(
            model_name='deleteordermessage',
            name='pitch_api_d_pitch_f_b08bd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='deleteordermessage',
            name='pitch_api_d_pitch_f_68fa11_idx',
        ),
        migrations.RemoveIndex(
            model_name='modifyordermessage',
            name='pitch_api_m_pitch_f_4c175f_idx',
        ),
        migrations.RemoveIndex(
            model_name='modifyordermessage',
            name='pitch_api_m_pitch_f_d6dcdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemeventmessage',
            name='pitch_api_s_pitch_f_7f4cd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemeventmessage',
            name='pitch_api_s_pitch_f_138754_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemeventmessage',
            name='pitch_api_s_pitch_f_8c8f4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradebreakmessage',
            name='pitch_api_t_pitch_f_727523_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradebreakmessage',
            name='pitch_api_t_pitch_f_d9c195_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradebreakmessage',
            name='pitch_api_t_pitch_f_e97afe_idx',
        ),
        migrations.RemoveField(
            model_name='auctionmessage',
            name='buy_shares',
        ),
        migrations.RemoveField(
            model_name='auctionmessage',
            name='indicative_price',
        ),
        migrations.RemoveField(
            model_name='auctionmessage',
            name='sell_shares',
        ),
        migrations.RemoveField(
            model_name='trademessage',
            name='execution_price',
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='message_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique ID for orders (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='participant_id',
            field=models.CharField(blank=True, help_text='Market participant identifier (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='pitch_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='pitch_api.pitchfile'),
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price of the order or trade', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of shares in the order/trade', null=True),
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='side',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', help_text="'B' = Buy, 'S' = Sell", max_length=1),
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='addordermessage',
            name='timestamp',
            field=models.BigIntegerField(default=0, help_text='Time the message was generated (nanoseconds)'),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='auction_type',
            field=models.CharField(default='O', help_text='Type of auction', max_length=1),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='message_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique ID for orders (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='participant_id',
            field=models.CharField(blank=True, help_text='Market participant identifier (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='pitch_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='pitch_api.pitchfile'),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price of the order or trade', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of shares in the order/trade', null=True),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='reference_price',
            field=models.DecimalField(decimal_places=8, default=0.0, help_text='Reference price of the auction', max_digits=19),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='auctionmessage',
            name='timestamp',
            field=models.BigIntegerField(default=0, help_text='Time the message was generated (nanoseconds)'),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='canceled_shares',
            field=models.IntegerField(default=0, help_text='Number of shares canceled'),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='message_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique ID for orders (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='participant_id',
            field=models.CharField(blank=True, help_text='Market participant identifier (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='pitch_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='pitch_api.pitchfile'),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price of the order or trade', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of shares in the order/trade', null=True),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cancelordermessage',
            name='timestamp',
            field=models.BigIntegerField(default=0, help_text='Time the message was generated (nanoseconds)'),
        ),
        migrations.AlterField(
            model_name='deleteordermessage',
            name='message_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deleteordermessage',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique ID for orders (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deleteordermessage',
            name='participant_id',
            field=models.CharField(blank=True, help_text='Market participant identifier (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='deleteordermessage',
            name='pitch_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='pitch_api.pitchfile'),
        ),
        migrations.AlterField(
            model_name='deleteordermessage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price of the order or trade', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='deleteordermessage',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of shares in the order/trade', null=True),
        ),
        migrations.AlterField(
            model_name='deleteordermessage',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='deleteordermessage',
            name='timestamp',
            field=models.BigIntegerField(default=0, help_text='Time the message was generated (nanoseconds)'),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='message_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='modified_shares',
            field=models.IntegerField(default=0, help_text='Updated number of shares'),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique ID for orders (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='participant_id',
            field=models.CharField(blank=True, help_text='Market participant identifier (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='pitch_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='pitch_api.pitchfile'),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price of the order or trade', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of shares in the order/trade', null=True),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='modifyordermessage',
            name='timestamp',
            field=models.BigIntegerField(default=0, help_text='Time the message was generated (nanoseconds)'),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='event_code',
            field=models.CharField(default='S', help_text='Code indicating the type of system event', max_length=1),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='message_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique ID for orders (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='participant_id',
            field=models.CharField(blank=True, help_text='Market participant identifier (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='pitch_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='pitch_api.pitchfile'),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price of the order or trade', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of shares in the order/trade', null=True),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='systemeventmessage',
            name='timestamp',
            field=models.BigIntegerField(default=0, help_text='Time the message was generated (nanoseconds)'),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='message_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique ID for orders (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='participant_id',
            field=models.CharField(blank=True, help_text='Market participant identifier (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='pitch_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='pitch_api.pitchfile'),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price of the order or trade', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of shares in the order/trade', null=True),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='timestamp',
            field=models.BigIntegerField(default=0, help_text='Time the message was generated (nanoseconds)'),
        ),
        migrations.AlterField(
            model_name='tradebreakmessage',
            name='trade_id',
            field=models.CharField(default='', help_text='ID of the trade being broken', max_length=50),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='executed_shares',
            field=models.IntegerField(default=0, help_text='Number of shares traded'),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='message_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='order_id',
            field=models.CharField(blank=True, help_text='Unique ID for orders (if applicable)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='participant_id',
            field=models.CharField(blank=True, help_text='Market participant identifier (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='pitch_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='pitch_api.pitchfile'),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Price of the order or trade', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Number of shares in the order/trade', null=True),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='symbol',
            field=models.CharField(blank=True, help_text='Stock symbol (if applicable)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='timestamp',
            field=models.BigIntegerField(default=0, help_text='Time the message was generated (nanoseconds)'),
        ),
        migrations.AlterField(
            model_name='trademessage',
            name='trade_id',
            field=models.CharField(default='', help_text='Unique trade ID', max_length=50),
        ),
        migrations.AddIndex(
            model_name='addordermessage',
            index=models.Index(fields=['pitch_file', 'order_id'], name='pitch_api_a_pitch_f_f5047f_idx'),
        ),
        migrations.AddIndex(
            model_name='addordermessage',
            index=models.Index(fields=['pitch_file', 'symbol'], name='pitch_api_a_pitch_f_602310_idx'),
        ),
        migrations.AddIndex(
            model_name='systemeventmessage',
            index=models.Index(fields=['pitch_file', 'event_code'], name='pitch_api_s_pitch_f_9140f3_idx'),
        ),
        migrations.AddIndex(
            model_name='tradebreakmessage',
            index=models.Index(fields=['pitch_file', 'trade_id'], name='pitch_api_t_pitch_f_0bdb34_idx'),
        ),
        migrations.AddIndex(
            model_name='trademessage',
            index=models.Index(fields=['pitch_file', 'order_id'], name='pitch_api_t_pitch_f_f10025_idx'),
        ),
    ]
